<a href="https://colab.research.google.com/github/kimanuul/python_lectures/blob/main/day0628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
title: "Python 기초함수"
date: '2022-06-28'
---

## 반복문 복습
- for loop and while loop

In [ ]:
for i in range(3):
  print("Hello World")
  print("안녕하세요")

Hello World
안녕하세요
Hello World
안녕하세요
Hello World
안녕하세요


In [ ]:
"K" in "Kaggle"
if "K" == "a":
  print("출력이 되나요?")
else:
  a = "Kaggle"

for i in range(1000):
  print("No.",i+1)
  if i == 10:
    break
  print("Hello World")
  print("안녕하세요")

No. 1
Hello World
안녕하세요
No. 2
Hello World
안녕하세요
No. 3
Hello World
안녕하세요
No. 4
Hello World
안녕하세요
No. 5
Hello World
안녕하세요
No. 6
Hello World
안녕하세요
No. 7
Hello World
안녕하세요
No. 8
Hello World
안녕하세요
No. 9
Hello World
안녕하세요
No. 10
Hello World
안녕하세요
No. 11


In [ ]:
a = "Kaggle"

for i in range(1000):
  print("No.",i+1)
  if i == 10:
    break
  

No. 1
No. 2
No. 3
No. 4
No. 5
No. 6
No. 7
No. 8
No. 9
No. 10
No. 11


In [ ]:
numbers = [1, 2, 3, 4, 5]
sum = 0

for num in numbers:
  # print("numbers: ", num)
  sum = sum + num
  # print("total: ", sum)
  print("---최종 결과값---")
  print(sum)

---최종 결과값---
1
---최종 결과값---
3
---최종 결과값---
6
---최종 결과값---
10
---최종 결과값---
15


In [ ]:
fruits = ['apple', 'kiwi', 'mango']
newlist = []

# apple : a가 있나요? 있네요. newlist에 추가하세요.
# kiwi : a가 있나요? 없네요. 그럼 넘어가요
# mango : a가 있나요? 있네요. newlist에 추가하세요.
for fruit in fruits:
   print("조건문 밖 : ", fruit)
   if "a" in fruit:
    print("조건문 안쪽 : ", fruit)
    newlist.append(fruit)

print(newlist)

조건문 밖 :  apple
조건문 안쪽 :  apple
조건문 밖 :  kiwi
조건문 밖 :  mango
조건문 안쪽 :  mango
['apple', 'mango']


## While Loop
while문 : 분석할 때 쓰일 일은 없음, 주로 개발(알고리즘)할 때 많이 씀

In [ ]:

i = 1
while i < 10: # 참일 때만 반복문 코드가 돎
  # 코드
  print(i)
  i += 1 # 1씩 증감
  # i -= 1 # 1씩 감소

1
2
3
4
5
6
7
8
9


## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성

In [ ]:
def 함수명(param1, param2):
  # 코드
  return None

In [ ]:
def add(a = 0, b = 1):
    return a + b

print(add(a = 5, b = 4))


9


- 사칙연산 사용자 정의 함수 만들기
- 함수 문서화
  + 키워드 : Docstring

In [ ]:
def add(a = 0, b = 0):
  return a + b
  
print(add(a = 3, b = 3 ))

6


In [ ]:
def sub(a = 0, b = 0):
  return a - b
  
print(sub(a = 3, b = 3 ))

0


In [ ]:
def mul(a = 0, b = 0):
  return a*b
  
print(mul(a = 3, b = 3 ))

9


In [ ]:
def div(a = 1, b = 1):
  return a/b
  
print(div(a = 3, b = 3 ))

1.0


In [ ]:
def add(a = 0, b = 0):
  return a + b

a = int(input("숫자1을 입력하세요..!"))
b = int(input("숫자2를 입력하세요..!"))

print(add(a, b))

숫자1을 입력하세요..!3
숫자2를 입력하세요..!3
6


In [ ]:
def subtract(a, b):

  """a, b를 빼는 함수
  Parameters:
  a(int): int형 숫자 a가 입력
  b(int): int형 숫자 b가 입력

  Returns:
    int : 반환값
  """
  return a - b

print(subtract(a = 5, b = 10))
print(subtract.__doc__)

-5
a, b를 빼는 함수
  Parameters:
  a(int): int형 숫자 a가 입력
  b(int): int형 숫자 b가 입력

  Returns:
    int : 반환값
  


## NumPy
- 두 개의 리스트(덧셈, 곱셈만 가능)를 행렬로 변환하여 나눌 수 있게 해줌
- 외장 모듈(내장 모듈, 라이브러리, 패키지가 아님, 별도 라이브러리 설치 필요)

In [ ]:
import numpy as np # np -> numpy
print(np.__version__)

1.21.6


In [ ]:
temp = [1, 2, 3]
temp_array = np.array(temp) # 리스트에서 배열로 변환

print(type(temp))
print(type(temp_array))

<class 'list'>
<class 'numpy.ndarray'>


## 사칙연

In [ ]:
math_score = [90, 80, 100, 60]
eng_score = [80, 90, 100, 50]

# math_score + eng_score

math_array = np.array(math_score)
eng_array = np.array(eng_score)

total = math_array + eng_array
print(total)
print(type(total))

[170 170 200 110]
<class 'numpy.ndarray'>


## 집계함수

In [ ]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

110
200
650


## 차원 확인
- 배열의 차원 확인 필요

In [ ]:
# 1차원 배열 생성
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim) # 차원을 확인하는 함수
print(temp_arr)

(3,)
1
[1 2 3]


In [ ]:
# 2차원 배열 생성
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [ ]:
## 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다.

In [ ]:
import numpy as np
print(np.__version__)  # 버젼 체크는 필수

1.21.6


In [ ]:
temp_arr = np.zeros((3, 3, 3)) # 3*3*3 행렬 생성
temp_arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

- 모두 1로 채운다

In [ ]:
temp_arr = np.ones((2, 3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다.

In [ ]:
temp_arr = np.full((3, 3,), 5)
temp_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- 최소, 최대 숫자의 범위를 정해두고 각 구간별로 값을 생성

In [ ]:
temp_arr = np.linspace(5, 10, 10) # 5에서 10 사이의 값 10개 
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시 자주 등장하는 배열 

In [ ]:
temp_arr = np.arange(1, 11, 1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 난수 생성
- 아래 둘은 같은 의미의 코드이다.

In [ ]:


from numpy import random
x = random.rand()
print(x)

0.19907248814642187


In [ ]:
import numpy
x = numpy.random.rand()
print(x)

0.5194615370225919


- 랜덤 정수값 추출

In [ ]:
from numpy import random
x = random.randint(100, size = (5))
print(x)
print(type(x))

[79  0 23 92 48]
<class 'numpy.ndarray'>


In [ ]:
import numpy
x = numpy.random.randint(100, size = (5))
print(x)
print(type(x))

[20 38 60 53 17]
<class 'numpy.ndarray'>


# 랜덤 배열, 실수값 추출

In [ ]:
from numpy import random
x = random.rand(2, 5)
print(x)
print(type(x))

[[0.9565263  0.54837567 0.96867699 0.48435514 0.87312763]
 [0.44631944 0.56557746 0.93989491 0.22650144 0.96368522]]
<class 'numpy.ndarray'>


# Numpy 사칙연산

In [ ]:
import numpy as np
array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

In [ ]:
# 덧셈
newArr = np.add(array_01, array_02)
print(newArr)

# 뺄셈
newArr = np.subtract(array_01, array_02)
print(newArr)

# 곱셈
newArr = np.multiply(array_01, array_02)
print(newArr)

# 나눗셈
newArr = np.divide(array_01, array_02)
print(newArr)

# 거듭제곱
array_01 = np.array([1, 2, 3])
array_02 = np.array([2, 2, 2])
newArr = np.power(array_01, array_02)
print(newArr)


[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[1 4 9]


## 소수점 정렬
- 소수점을 정렬하는 다양한 방법

In [ ]:
# 소수점 제거
import numpy as np
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
[-1.  1.]


In [ ]:
# 임의의 소수점 자리에서 반올림
temp_arr = np.around([-1.23456, 1.23456], 3) # 소수점 세번째 자리에서 반올림
print(temp_arr)

[-1.235  1.235]


In [ ]:
# 소수점 내림
temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)

[-2.  1.]


In [ ]:
# 소수점 모두 올림
temp_arr = np.ceil([-1.23456, 1.23456])
print(temp_arr)

[-1.  2.]


## 조건식
- pandas 가공
- numpy
- 조건식
  + 하나의 조건식(=np.where)
  + 다중 조건식


In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 5보다 작의면 원값 유지
# 5보다 크면 곱하기 10을 해줌

In [ ]:
# np.where(조건식, 참일 때, 거짓일 때)
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
temp_arr = np.arange(10)
# temp_arr
cond_list   = [temp_arr > 5, temp_arr <2 ]
choice_list = [temp_arr *2, temp_arr + 100]

# np.selsect(조건식 리스트, 결과값 리스트, default = )
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
- 배열의 차원 또는 크기를 바꾼다.
- 곱셈만 할 줄 알면 끝

In [ ]:
import numpy as np
temp_array = np.ones((3, 4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
after_reshape = temp_array.reshape(2, 2, 3) # 곱이 12
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
# 원하는 자리값을 넣고 남은 곳에 -1을 넣어주면 데이터 값에 맞는 자리값을 설정해준다.
after_reshape = temp_array.reshape(2, 2, -1)
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 브로드 캐스팅
- 서로 다른 크기의 배열을 계산할 때의 기본적인 규칙을 의미

# pandas 튜토리얼

In [ ]:
import pandas as pd
print(pd.__version__)

1.3.5


In [ ]:
temp_dict = {
    'col1' : [1, 2],
    'col2' : [3, 4]
}

df = pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/'
print(DATA_PATH + 'Lemonade2016.csv')

lemonade = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
#covid_df = pd.read_csv(DATA_PATH + 'owid-covid-data.csv')

lemonade.info # 파일이 잘 들어왔는지 확인

/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/Lemonade2016.csv


<bound method DataFrame.info of          Date Location  Lemon  Orange  Temperature  Leaflets  Price
0    7/1/2016     Park     97      67           70      90.0   0.25
1    7/2/2016     Park     98      67           72      90.0   0.25
2    7/3/2016     Park    110      77           71     104.0   0.25
3    7/4/2016    Beach    134      99           76      98.0   0.25
4    7/5/2016    Beach    159     118           78     135.0   0.25
5    7/6/2016    Beach    103      69           82      90.0   0.25
6    7/6/2016    Beach    103      69           82      90.0   0.25
7    7/7/2016    Beach    143     101           81     135.0   0.25
8         NaN    Beach    123      86           82     113.0   0.25
9    7/9/2016    Beach    134      95           80     126.0   0.25
10  7/10/2016    Beach    140      98           82     131.0   0.25
11  7/11/2016    Beach    162     120           83     135.0   0.25
12  7/12/2016    Beach    130      95           84      99.0   0.25
13  7/13/2016   